### ISSUE TITLE
Some paths missing from SVG generated by Gingerbread

### ISSUE THREAD

**Issue by jasonbirchler** [wntrblm/Gingerbread#11]
Hello 👋
I am seeing odd behavior where some paths are missing after exporting from Affinity Designer, importing to Gingerbread and opening the resulting `.kicad_pcb` file in PCBNew. The paths in question are visible in both Designer and the Gingerbread preview, as expected. In some cases, the missing paths are part of a font, in other cases they were paths to begin with.

I first noticed this when I significantly increased the number of paths in my design (from 10’s to 100’s). But even after stripping back the total number I see the same issue.

Things I have tried that did not work for fonts:
1. As mentioned, dramatically reduced total number of paths in Designer before export
2. Convert fonts to paths in Designer before export
3. Let Designer convert fonts to paths as part of export

Things I have tried that did not work for pure paths (i.e. not fonts):
1. Reverting back to a simple group of paths (i.e. one rectangle for every “square” in the screenshot)
2. Grouping all the paths
3. Manually editing the joined path to simplify as much as possible
4. Deleting the paths that end up missing in the `.kicad_pcb` file from the Designer file and manually drawing new paths before re-exporting

Visually, this appears to be related to when 2 paths touch, or share a single point. If you look at the 2 screenshots, all of the missing paths share a corner point. But not all paths that share a corner are missing in the resulting `.kicad_pcb`.

Have I simply bumped up against the upper limit of the number of paths Gingerbread can convert? Maybe I designed my little “pixel grid” such that when it gets converted to BMP certain path intersections are seen as “0” when I expected a “1”? Or maybe something else entirely?

<img width="223" alt="Screenshot 2024-11-10 at 3 20 36 PM" src="https://github.com/user-attachments/assets/3d2ddb95-f4ba-492d-a544-9578c9840088">
<img width="213" alt="Screenshot 2024-11-10 at 3 20 25 PM" src="https://github.com/user-attachments/assets/dd57c97c-605b-4120-910f-8e11bf01fee8">
<img width="590" alt="Screenshot 2024-11-10 at 3 43 26 PM" src="https://github.com/user-attachments/assets/62462c86-5df5-4b37-93dc-1be58920eb27">
<img width="715" alt="Screenshot 2024-11-10 at 3 43 14 PM" src="https://github.com/user-attachments/assets/4264105a-035a-4e50-8ecd-2f33c1b658c8">

**Comment by theacodes** [comment]
It's difficult to diagnose without the exact file, but it's possible these are just too small and are getting removed by the "crud" filter in the vector -> bitmap -> vector process.

**Comment by jasonbirchler** [comment]
Increasing the size of the squares fixed the problem. I’m now confident this was user error. Closing.
