### ISSUE TITLE
SVG Design is not showing

### ISSUE THREAD

**Issue by M4rkoV2** [wntrblm/Gingerbread#8]
I want to upload [this SVG](https://www.svgrepo.com/svg/287560/earth) icon in gingerboard but is not showing anything.

<img width="500" alt="Posnetek zaslona 2024-08-04 110559" src="https://github.com/user-attachments/assets/886a177b-b440-4f1f-94fd-aebde7ca9b17">

It doesn't work on Edge or Chrome. I also try other svg files from svgrepo.com and none seems to work.

**Comment by theacodes** [comment]
Hi, Gingerbread isn't intended to work with generic SVGs. Designs need to be prepared in specific ways in order to work with Gingerbread, please take a look at the documentation here: https://gingerbread.wntr.dev/help.html
